#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/vsmart/casuarina

PRODUCT_COPY_FILES += \
    vendor/vsmart/casuarina/proprietary/vendor/etc/acdbdata/QRD/msm8953-sku4-snd-card/QRD_SKU4_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8953-sku4-snd-card/QRD_SKU4_Bluetooth_cal.acdb \
    vendor/vsmart/casuarina/proprietary/vendor/etc/acdbdata/QRD/msm8953-sku4-snd-card/QRD_SKU4_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8953-sku4-snd-card/QRD_SKU4_General_cal.acdb \
    vendor/vsmart/casuarina/proprietary/vendor/etc/acdbdata/QRD/msm8953-sku4-snd-card/QRD_SKU4_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8953-sku4-snd-card/QRD_SKU4_Global_cal.acdb \
    vendor/vsmart/casuarina/proprietary/vendor/etc/acdbdata/QRD/msm8953-sku4-snd-card/QRD_SKU4_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8953-sku4-snd-card/QRD_SKU4_Handset_cal.acdb \
    vendor/vsmart/casuarina/proprietary/vendor/etc/acdbdata/QRD/msm8953-sku4-snd-card/QRD_SKU4_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8953-sku4-snd-card/QRD_SKU4_Hdmi_cal.acdb \
    vendor/vsmart/casuarina/proprietary/vendor/etc/acdbdata/QRD/msm8953-sku4-snd-card/QRD_SKU4_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8953-sku4-snd-card/QRD_SKU4_Headset_cal.acdb \
    vendor/vsmart/casuarina/proprietary/vendor/etc/acdbdata/QRD/msm8953-sku4-snd-card/QRD_SKU4_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8953-sku4-snd-card/QRD_SKU4_Speaker_cal.acdb \
    vendor/vsmart/casuarina/proprietary/vendor/etc/acdbdata/QRD/msm8953-sku4-snd-card/QRD_SKU4_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8953-sku4-snd-card/QRD_SKU4_workspaceFile.qwsp \
    vendor/vsmart/casuarina/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/vsmart/casuarina/proprietary/vendor/etc/camera/gc2385_casuarina_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/gc2385_casuarina_chromatix.xml \
    vendor/vsmart/casuarina/proprietary/vendor/etc/camera/ov8856_casuarina_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov8856_casuarina_chromatix.xml \
    vendor/vsmart/casuarina/proprietary/vendor/etc/camera/s5k3l6_casuarina_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3l6_casuarina_chromatix.xml \
    vendor/vsmart/casuarina/proprietary/vendor/etc/camera/s5k4h7yx_casuarina_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k4h7yx_casuarina_chromatix.xml \
    vendor/vsmart/casuarina/proprietary/vendor/etc/camera/v430_camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/v430_camera.xml \
    vendor/vsmart/casuarina/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/vsmart/casuarina/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/vsmart/casuarina/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/vsmart/casuarina/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/vsmart/casuarina/proprietary/vendor/etc/wifi/WCNSS_qcom_wlan_nv_v430mp_v1.5.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/WCNSS_qcom_wlan_nv_v430mp_v1.5.bin \
    vendor/vsmart/casuarina/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/vsmart/casuarina/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/vsmart/casuarina/proprietary/vendor/firmware/cpp_firmware_v1_12_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_1.fw \
    vendor/vsmart/casuarina/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/vsmart/casuarina/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/vsmart/casuarina/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/vsmart/casuarina/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/vsmart/casuarina/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/vsmart/casuarina/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/vsmart/casuarina/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/vsmart/casuarina/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/vsmart/casuarina/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw

PRODUCT_PACKAGES += \
    camera.msm8953 \
    libactuator_dw9714_casuarina \
    libarcsoft_beautyshot \
    libarcsoft_dualcam_refocus_image \
    libarcsoft_dualcam_refocus_video \
    libarcsoft_hdr_detection \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_low_light_shot \
    libarcsoft_singlecam_bokeh \
    libcamera2ndk_vendor \
    libcapiv2svacnn \
    libcapiv2vop \
    libchromatix_csidtg_common \
    libchromatix_csidtg_cpp_preview \
    libchromatix_csidtg_postproc \
    libchromatix_csidtg_preview \
    libchromatix_csidtg_zsl_preview \
    libchromatix_gc2385_casuarina_common \
    libchromatix_gc2385_casuarina_cpp_preview \
    libchromatix_gc2385_casuarina_postproc \
    libchromatix_gc2385_casuarina_snapshot \
    libchromatix_gc2385_casuarina_zsl_preview \
    libchromatix_ov8856_casuarina_a3_default_preview \
    libchromatix_ov8856_casuarina_a3_default_video \
    libchromatix_ov8856_casuarina_a3_hfr_120 \
    libchromatix_ov8856_casuarina_a3_hfr_60 \
    libchromatix_ov8856_casuarina_a3_hfr_90 \
    libchromatix_ov8856_casuarina_common \
    libchromatix_ov8856_casuarina_cpp_ds_chromatix \
    libchromatix_ov8856_casuarina_cpp_hfr_120 \
    libchromatix_ov8856_casuarina_cpp_hfr_60 \
    libchromatix_ov8856_casuarina_cpp_hfr_90 \
    libchromatix_ov8856_casuarina_cpp_liveshot \
    libchromatix_ov8856_casuarina_cpp_preview \
    libchromatix_ov8856_casuarina_cpp_snapshot \
    libchromatix_ov8856_casuarina_cpp_us_chromatix \
    libchromatix_ov8856_casuarina_cpp_video \
    libchromatix_ov8856_casuarina_default_video \
    libchromatix_ov8856_casuarina_hfr_120 \
    libchromatix_ov8856_casuarina_hfr_60 \
    libchromatix_ov8856_casuarina_hfr_90 \
    libchromatix_ov8856_casuarina_liveshot \
    libchromatix_ov8856_casuarina_postproc \
    libchromatix_ov8856_casuarina_preview \
    libchromatix_ov8856_casuarina_snapshot \
    libchromatix_ov8856_casuarina_zsl_preview \
    libchromatix_ov8856_casuarina_zsl_video \
    libchromatix_s5k3l6_casuarina_common \
    libchromatix_s5k3l6_casuarina_cpp_hfr_120 \
    libchromatix_s5k3l6_casuarina_cpp_hfr_60 \
    libchromatix_s5k3l6_casuarina_cpp_hfr_90 \
    libchromatix_s5k3l6_casuarina_cpp_liveshot \
    libchromatix_s5k3l6_casuarina_cpp_preview \
    libchromatix_s5k3l6_casuarina_cpp_snapshot \
    libchromatix_s5k3l6_casuarina_cpp_video \
    libchromatix_s5k3l6_casuarina_default_preview_3a \
    libchromatix_s5k3l6_casuarina_default_video \
    libchromatix_s5k3l6_casuarina_default_video_3a \
    libchromatix_s5k3l6_casuarina_dualcam_zsl_preview_3a \
    libchromatix_s5k3l6_casuarina_dualcamsnapshot \
    libchromatix_s5k3l6_casuarina_hfr_120 \
    libchromatix_s5k3l6_casuarina_hfr_120_3a \
    libchromatix_s5k3l6_casuarina_hfr_60 \
    libchromatix_s5k3l6_casuarina_hfr_60_3a \
    libchromatix_s5k3l6_casuarina_hfr_90 \
    libchromatix_s5k3l6_casuarina_hfr_90_3a \
    libchromatix_s5k3l6_casuarina_liveshot \
    libchromatix_s5k3l6_casuarina_lls2_zsl_preview_3a \
    libchromatix_s5k3l6_casuarina_lls2snapshot \
    libchromatix_s5k3l6_casuarina_lls_zsl_preview_3a \
    libchromatix_s5k3l6_casuarina_llssnapshot \
    libchromatix_s5k3l6_casuarina_postproc \
    libchromatix_s5k3l6_casuarina_preview \
    libchromatix_s5k3l6_casuarina_snapshot \
    libchromatix_s5k3l6_casuarina_zsl_preview_3a \
    libchromatix_s5k3l6_casuarina_zsl_video_3a \
    libchromatix_s5k4h7yx_casuarina_a3_zsl_preview \
    libchromatix_s5k4h7yx_casuarina_common \
    libchromatix_s5k4h7yx_casuarina_cpp_snapshot \
    libchromatix_s5k4h7yx_casuarina_postproc \
    libchromatix_s5k4h7yx_casuarina_snapshot \
    libdepthmapwrapper \
    libflash_pmic \
    libhal_dbg \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera2_stats_modules \
    libmmcamera_arcrtb_wrapper_lib \
    libmmcamera_atmel_at24c32e_eeprom \
    libmmcamera_bokeh \
    libmmcamera_csidtg \
    libmmcamera_dbg \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_gc2385_casuarina \
    libmmcamera_hdr_gb_lib \
    libmmcamera_holitech_ov8856_casuarina_eeprom \
    libmmcamera_hongshi_s5k3l6_casuarina_eeprom \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_interface \
    libmmcamera_irs1645 \
    libmmcamera_isp_abf40 \
    libmmcamera_isp_bcc40 \
    libmmcamera_isp_be_stats44 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats44 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_bpc40 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct40 \
    libmmcamera_isp_color_xform_encoder40 \
    libmmcamera_isp_color_xform_viewfinder40 \
    libmmcamera_isp_cs_stats44 \
    libmmcamera_isp_demosaic40 \
    libmmcamera_isp_demux40 \
    libmmcamera_isp_fovcrop_encoder40 \
    libmmcamera_isp_fovcrop_viewfinder40 \
    libmmcamera_isp_gamma40 \
    libmmcamera_isp_ihist_stats44 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm44 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff40 \
    libmmcamera_isp_rs_stats44 \
    libmmcamera_isp_scaler_encoder44 \
    libmmcamera_isp_scaler_viewfinder44 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_sub_module \
    libmmcamera_isp_template \
    libmmcamera_isp_wb40 \
    libmmcamera_ov8856_4lane_casuarina \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_s5k3l6_casuarina \
    libmmcamera_s5k4h7yx_casuarina \
    libmmcamera_sat_test_lib \
    libmmcamera_stillmore_lib \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_tsp_s5k4h7_casuarina_eeprom \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmpbase \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libseemore \
    libvideoutils \
    libpn547_fw \
    libFastRPC_AUE_Forward_skel \
    libFastRPC_UTF_Forward_Qtc2_skel \
    libadsp_fd_skel \
    libapps_mem_heap \
    libdspCV_skel \
    libfastcvadsp \
    libfastcvadsp_skel \
    libscveBlobDescriptor_skel \
    libscveObjectSegmentation_skel \
    libscveT2T_skel \
    mm-qcamera-app

PRODUCT_PACKAGES += \
    vendor_firmware_wlan_prima_WCNSS_qcom_wlan_nv_bin
